### PR TITLE
Publish docling-serve images to ghcr and quay container repositories

### PR DESCRIPTION
**Pull request by vishnoianil**
This commit:
- Creates container file to build the image for cpu only and default "with gpu" images
- Adds workflow jobs to publish the images to ghcr.io and quay.io
- Makefile to build these images locally for linux/amd64 platform.

### CODE REVIEW

**Comment by vishnoianil** [comment]
Pending:

- [x] local build for both mode
- [x] possible image optimization

**Comment by vishnoianil** [comment]
The size of cpu only image is around 3.5G and with GPU dependency it's around 7.5G.

**Comment by vishnoianil** [comment]
@dolfim-ibm PTAL and let me know if you have thoughts.

**Review by dolfim-ibm — APPROVED** [review]
🚀 great!

**Pull request merged**
